name: Remote deployment
on:
  push:
    branches: [ main ]

jobs:
  deployJob:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.AUTOGIT_SSHKEY }}
        port: 22
        script: |
          cd /srv/shiny-server/legoxcovid/
          git pull
          git status
          
